name: Example Action

on:
  push:
    branchs : [testing]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install NPM Install
        run: npm ci

      - name: Build Project
        run: npm run build
        env:
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}

      - name: Test Build
        run: npm run test