name: Example Action

on:
  push:
    branchs : [testing]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name : Cache node modules
        id: cache-npm
        uses: actions/cache@v6
        with:
          path: node_module
          key: ${{ runner.os}}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install NPM Install
        run: npm ci

      - name: Build Project
        run: npm run build
        env:
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}

      - name: Upload Build to artifact
        uses: actions/upload-artifact
        with:
          name: next-build
          path: .next
          inclue-hiddel-files: true
          retention-days: 1

